### ISSUE TITLE
Japanese translation is inaccurate

### ISSUE THREAD

**Issue by hmatsumu** [NetAppDocs/bluexp-backup-recovery.ja-jp#1]
### Page URL

https://docs.netapp.com/ja-jp/bluexp-backup-recovery/concept-cloud-backup-policies.html

### Page title

BlueXPのバックアップ/リカバリポリシーの設定

### Summary

Japanese translation needs to be more accurate.

Original English:
Be aware that old backups are deleted after the DataLock Retention Period expires, not after the backup policy retention period expires.

Translation on Japanese page:
古いバックアップは、バックアップポリシーの保持期間が過ぎても、DataLockの保持期間が過ぎると削除されるのではなく、注意してください。

Suggestion:
古いバックアップは、バックアップポリシーの保持期間が終了した後ではなく、DataLockの保持期間が終了した後に削除されることに注意してください。

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-gudugunti** [comment]
Thanks! @hmatsumu for reporting the issue,
We shall look into it and get back to you.

**Comment by netapp-gudugunti** [comment]
Thanks! for reporting this issue, @hmatsumu.
Your suggestion has been implemented.
The issue has been fixed.
